baseurl = "https://hillpy.com/"
title = "Hillpy"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
    series = "series"

[params]
    author = "shinn_lancelot"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        沈宝宝家的奶爸，
        喜欢ACGM的码农~
    """
    publicationYear = "2019"
    listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/custom.css"]
    custom_js = ["/js/custom.js"]
    icp = ""
    organization = "hillpy"

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    name = "Blog"
    pre = "<img src='./common/image/blog_1.png' class='icon'>"
    url = "/blog/"
    weight = 10

[[menu.main]]
    name = "GitHub"
    pre = "<img src='./common/image/github.png' class='icon'>"
    url = "https://github.com/shinn-lancelot"
    weight = 20

[[menu.main]]
    name = "Bilibili"
    pre = "<img src='./common/image/bilibili_1.png' class='icon'>"
    url = "https://space.bilibili.com/7427491"
    weight = 30

[[menu.main]]
    name = "Juejin"
    pre = "<img src='./common/image/juejin.png' class='icon'>"
    url = "https://juejin.im/user/5968cf826fb9a06ba64664d5"
    weight = 40

[[menu.main]]
    name = "Learnku"
    pre = "<img src='./common/image/learnku.png' class='icon'>"
    url = "https://learnku.com/users/32268"
    weight = 50

[[menu.main]]
    name = "Zhihu"
    pre = "<img src='./common/image/zhihu_1.png' class='icon'>"
    url = "https://www.zhihu.com/people/lancelot-shinn"
    weight = 60

[[menu.main]]
    name = "Wechat"
    pre = "<img src='./common/image/wechat.png' class='icon'>"
    url = "./common/image/wechat_qrcode.jpg"
    weight = 70

[[menu.main]]
    name = "QQ"
    pre = "<img src='./common/image/qq_1.png' class='icon'>"
    url = "./common/image/qq_qrcode.jpg"
    weight = 80

[[menu.main]]
    name = "Email"
    pre = "<img src='./common/image/gmail.png' class='icon'>"
    url = "mailto:lanhaichun0317@gmail.com"
    weight = 90